# Generated by Django 4.2.7 on 2023-12-12 12:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('experience', models.FloatField()),
                ('score', models.FloatField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures')),
            ],
        ),
    ]
