# Generated by Django 4.2.7 on 2023-12-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, null=True)),
                ('phone', models.CharField(max_length=13)),
                ('experience', models.IntegerField()),
                ('score', models.FloatField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures')),
            ],
        ),
    ]
