# Generated by Django 4.2.7 on 2023-12-17 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_uz', models.CharField(max_length=100)),
                ('type_ru', models.CharField(max_length=100)),
                ('description_uz', models.CharField()),
                ('description_ru', models.CharField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name_uz', models.CharField(max_length=100)),
                ('course_name_ru', models.CharField(max_length=100)),
                ('duration_uz', models.CharField(max_length=50)),
                ('duration_ru', models.CharField(max_length=50)),
                ('students_number', models.IntegerField()),
                ('price', models.FloatField(max_length=20)),
                ('lectures_uz', models.CharField(max_length=30)),
                ('lectures_ru', models.CharField(max_length=30)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
    ]
