# Generated by Django 4.2.7 on 2023-12-12 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0002_alter_teacher_experience_alter_teacher_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('students_number', models.IntegerField()),
                ('price', models.FloatField(max_length=20)),
                ('lectures', models.CharField(max_length=30)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
    ]
