# Generated by Django 4.2.7 on 2023-12-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('description', models.CharField()),
            ],
        ),
    ]
