# Generated by Django 4.2.7 on 2023-12-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='picture',
            new_name='picture_ru',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='type',
            new_name='type_ru',
        ),
        migrations.AddField(
            model_name='category',
            name='description_uz',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='picture_uz',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='category',
            name='type_uz',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
