# Generated by Django 4.2.7 on 2023-12-12 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_description_category_description_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='picture_ru',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='category',
            name='picture_uz',
        ),
    ]
