# Generated by Django 4.2.7 on 2023-12-25 11:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('student_numer', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('parents_numer', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('course_language_uz', models.CharField(choices=[("O'zbek", "O'zbek"), ('Rus', 'Rus')], max_length=30)),
                ('course_language_ru', models.CharField(choices=[('Узбек', 'Узбек'), ('Русский', 'Русский')], max_length=30)),
                ('status', models.CharField(choices=[('New', 'New'), ('Disagreement', 'Disagreement'), ('Agreement', 'Agreement')], default='New', max_length=50)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
        ),
    ]
