# Generated by Django 4.2.7 on 2023-12-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='course_language_ru',
            field=models.CharField(choices=[('Узбек', 'Узбек'), ('Русский', 'Русский')], max_length=30),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='course_language_uz',
            field=models.CharField(choices=[("O'zbek", "O'zbek"), ('Rus', 'Rus')], max_length=30),
        ),
    ]
